export default {
    keys: {
        DOCKSTATION_DOCKER_API: 'DOCKSTATION_DOCKER_API',
        DOCKSTATION_IS_DEBUG: 'DOCKSTATION_IS_DEBUG',
        DEFAULT_PASSWORD: 'DEFAULT_PASSWORD',
        IS_DOCKSTATION_INSTANCE: 'IS_DOCKSTATION_INSTANCE',
        DEMO_MODE_ADMIN_IP: 'DEMO_MODE_ADMIN_IP',
    },

    BY_PASS_PROXY_CHECK: process.env.BY_PASS_PROXY_CHECK,

    DOCKSTATION_DOCKER_API: process.env.DOCKSTATION_DOCKER_API,

    DOCKSTATION_IS_DEBUG: !!process.env.DOCKSTATION_IS_DEBUG,

    MAIN_NODE_IP_ADDRESS: process.env.MAIN_NODE_IP_ADDRESS,

    ACCEPTED_TERMS: !!process.env.ACCEPTED_TERMS,

    IS_DOCKSTATION_INSTANCE: process.env.IS_DOCKSTATION_INSTANCE,

    DEMO_MODE_ADMIN_IP: process.env.DEMO_MODE_ADMIN_IP,

    DEFAULT_PASSWORD: process.env.DEFAULT_PASSWORD,

    FORCE_ENABLE_PRO: process.env.FORCE_ENABLE_PRO,

    CAPROVER_DISABLE_ANALYTICS:
        !!process.env.CAPROVER_DISABLE_ANALYTICS || !!process.env.DO_NOT_TRACK,
}
